#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Borek Data Ventures UG
# =============================================================================
# Sovereign Agentic OS — install wizard (works-out-of-the-box).
# =============================================================================
# Press Enter through every prompt for the fully self-contained install (Mode A:
# every backend bundled in the chart). Or opt specific backends into managed/
# external services. See stackit/packaging.md.
#
#   ./install.sh                 # interactive
#   ./install.sh --defaults      # non-interactive, all bundled (CI / quick)
#   ./install.sh --uninstall     # remove the release (keeps the cluster)
# =============================================================================
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"; cd "$ROOT"
CHART="charts/sovereign-agentic-os"
RELEASE="agentic-os"; NS="agentic-os"; CLUSTER="agentic-os"
GEN="values.generated.yaml"
DEFAULTS=0; UNINSTALL=0
for a in "$@"; do case "$a" in --defaults) DEFAULTS=1;; --uninstall) UNINSTALL=1;; esac; done

c() { printf "\033[1;36m%s\033[0m\n" "$*"; }      # cyan heading
ok() { printf "\033[1;32m✓ %s\033[0m\n" "$*"; }
ask() { # ask "Question" "default"  -> echoes answer
  local q="$1" def="${2:-}"; local ans=""
  if [ "$DEFAULTS" = 1 ]; then echo "$def"; return; fi
  read -r -p "$(printf '\033[1m%s\033[0m [%s]: ' "$q" "$def")" ans </dev/tty || true
  echo "${ans:-$def}"
}
backend() { # backend "Name" "valuesKey"  -> appends mode to $GEN
  local name="$1" key="$2"
  local m; m="$(ask "  $name backend — 'bundled' (Enter) or external endpoint" "bundled")"
  if [ "$m" = "bundled" ]; then
    echo "  # $name: bundled" >> "$GEN"
  else
    echo "  # $name: external ($m)" >> "$GEN"
    printf '%s:\n  mode: external\n  external:\n    endpoint: %q\n' "$key" "$m" >> "$GEN"
  fi
}

if [ "$UNINSTALL" = 1 ]; then
  c "Uninstalling $RELEASE…"; helm uninstall "$RELEASE" -n "$NS" || true
  ok "Release removed (cluster + operators kept; 'kind delete cluster --name $CLUSTER' to remove the cluster)."; exit 0
fi

c "Sovereign Agentic OS — install wizard"
echo "Press Enter to accept the default (fully self-contained) at every prompt."
echo

# --- 1. target -------------------------------------------------------------
TARGET="$(ask "Target cluster: kind / stackit / other" "kind")"

# --- 2. STACKIT-managed shortcut ------------------------------------------
ALL_MANAGED="no"
if [ "$TARGET" = "stackit" ]; then
  ALL_MANAGED="$(ask "Use ALL STACKIT-managed backends? (yes/no)" "no")"
fi

# --- 3. write the generated overlay ---------------------------------------
{
  echo "# Generated by install.sh — do not edit by hand."
  echo "global:"
  echo "  profile: $([ "$TARGET" = stackit ] && echo stackit || echo local)"
} > "$GEN"

if [ "$ALL_MANAGED" = "yes" ]; then
  c "Selecting all-STACKIT-managed preset…"
  PRESET="values.stackit-managed.yaml"
  echo "# (all backends -> STACKIT managed; see $PRESET)" >> "$GEN"
  echo "Run deploy/terraform to provision the managed services, then re-run with the SA key."
else
  PRESET="values.selfcontained.yaml"
  c "Per-backend choice (Enter = bundled / self-contained):"
  backend "Postgres"        "postgres"
  backend "OpenSearch"      "opensearch"
  backend "Object storage"  "objectStorage"
  backend "Cache (Valkey)"  "valkey"
  echo
  c "LLM endpoint:"
  LLM="$(ask "  'local' tiny mock (Enter) / openai / azure / mistral / stackit / vllm" "local")"
  if [ "$LLM" != "local" ]; then
    KEY="$(ask "  API key or model-serving token (stored as a k8s secret ref name)" "litellm-provider-key")"
    printf 'llm:\n  mode: external\n  provider: %q\n  secretRef: %q\n' "$LLM" "$KEY" >> "$GEN"
  fi
fi
ok "Wrote $GEN"

# --- 4. prerequisites ------------------------------------------------------
if [ "$TARGET" = "kind" ]; then
  if ! kind get clusters 2>/dev/null | grep -qx "$CLUSTER"; then
    c "Creating kind cluster '$CLUSTER'…"; kind create cluster --name "$CLUSTER" --config kind-config.yaml
  else ok "kind cluster '$CLUSTER' already exists"; fi
  kubectl config use-context "kind-$CLUSTER" >/dev/null 2>&1 || true
fi

c "Bootstrapping cluster-scoped operators (CloudNativePG)…"
./scripts/bootstrap-local.sh

if [ "$TARGET" = "kind" ]; then
  c "Building + loading the bespoke images into kind…"
  ./scripts/build-images.sh "$CLUSTER"
fi

# --- 5. install ------------------------------------------------------------
c "Fetching chart dependencies…"; helm dependency build "$CHART" >/dev/null
c "Installing the Sovereign Agentic OS (this takes a few minutes)…"
helm upgrade --install "$RELEASE" "$CHART" -n "$NS" --create-namespace \
  -f "$PRESET" -f "$GEN" --timeout 12m

# --- 6. demo seed + registry pull config -----------------------------------
# The demo seed (knowledge index, dbt warehouse, Iceberg table, Superset dataset,
# Forgejo repo -> CI -> Argo app, Langfuse project + keys, demo logins) is applied
# by the chart's post-install hooks automatically.
# Configure the node to pull CI-built images from Forgejo's in-cluster registry
# (so the software golden path's deployed image resolves).
if [ "$TARGET" = "kind" ]; then
  c "Configuring the node registry pull (Forgejo in-cluster registry)…"
  ./scripts/configure-registry.sh "${CLUSTER}-control-plane" "$NS" || \
    echo "  (non-fatal; re-run ./scripts/configure-registry.sh if the demo-app image won't pull)"
fi
ok "Install complete."

# --- 7. report -------------------------------------------------------------
cat <<EOF

$(c "Start here — one front door:")
  OS UI (product + ops) kubectl -n $NS port-forward svc/os-ui 8080:3000
                        -> http://localhost:8080   (Home / Agents / Structured Data / Monitoring / Dashboards)
                        -> Platform -> Components   (every component's status, on/off, login + docs)

$(c "Demo logins (port-forward, then open in a browser):")
  Langfuse (traces)     kubectl -n $NS port-forward svc/agentic-os-langfuse-web 3000:3000
                        -> http://localhost:3000   admin@datamasterclass.com / langfuse-local-dev-admin
  LiteLLM (gateway)     kubectl -n $NS port-forward svc/agentic-os-litellm 4000:4000
                        -> http://localhost:4000/ui   admin / litellm-admin-local-dev
  Superset (dashboards) kubectl -n $NS port-forward svc/agentic-os-superset 8088:8088
                        -> http://localhost:8088   admin / superset-admin-local-dev
  Argo CD (GitOps)      kubectl -n $NS port-forward svc/argocd-server 8080:80
                        -> http://localhost:8080   admin / (kubectl -n $NS get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d)
  Forgejo (git)         kubectl -n $NS port-forward svc/forgejo-http 3001:3000
                        -> http://localhost:3001   gitea_admin / forgejo-admin-local-dev

$(c "Try it:")
  # RAG agent:
  kubectl -n $NS run ask --rm -i --restart=Never --image=curlimages/curl:8.11.1 -- \\
    curl -sS http://sample-agent:8000/ask -G --data-urlencode "q=What is the retrieval backbone?"
  # Trino query over the lakehouse via the governed query-tool / LiteLLM MCP gateway: see README.

Uninstall: ./install.sh --uninstall   (or 'kind delete cluster --name $CLUSTER')
EOF
