// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Borek Data Ventures UG (haftungsbeschränkt)

package install

import (
	"fmt"
	"strings"
)

// RenderInstallValues produces the small install.yaml overlay: ONLY the admin's
// answers, expressed as chart values, to be layered on top of the base
// values.yaml + the per-cloud overlay (values.<cloud>.yaml). It contains no
// secrets — object-storage / LLM auth is keyless (Workload Identity / Pod
// Identity / Entra WI), so this file carries names and ids, never credentials.
//
// The output is hand-rolled YAML (not a struct marshal) so it stays readable,
// commented, and stable field-order for tests — matching the house style of the
// existing values overlays. Deterministic given the same Answers.
func RenderInstallValues(a Answers) string {
	var b strings.Builder

	b.WriteString("# =============================================================================\n")
	b.WriteString("# install.yaml — generated by `sos install` (admin answers only).\n")
	b.WriteString("# =============================================================================\n")
	fmt.Fprintf(&b, "# Layered LAST, on top of the chart base values.yaml and the per-cloud overlay\n")
	fmt.Fprintf(&b, "# %s. Holds ONLY what the admin chose; every backend detail (keyless\n", a.ValuesFile())
	b.WriteString("# identity, catalog wiring) comes from the overlay. No sensitive values here.\n")
	b.WriteString("# =============================================================================\n\n")

	fmt.Fprintf(&b, "global:\n  cloud: %s\n  region: %q\n\n", a.Cloud, a.Region)

	// --- Object storage (bucket only; auth is keyless via the SA identity) ---
	if a.Cloud != CloudKind {
		b.WriteString("# Object storage — bucket/container the overlay's keyless SA writes to\n")
		b.WriteString("# (warehouse data + Postgres WAL archive share this bucket).\n")
		fmt.Fprintf(&b, "objectStorage:\n  bucket: %q\n\n", a.Bucket)
	}

	// --- Postgres engine choice ---------------------------------------------
	b.WriteString("# Postgres engine (report §1: CNPG is the cloud default; plain for local/STACKIT).\n")
	switch a.Postgres {
	case PostgresExternal:
		b.WriteString("postgres:\n  enabled: false  # external managed Postgres — set external.host in the overlay\n\n")
	default:
		fmt.Fprintf(&b, "postgres:\n  enabled: true\n  engine: %s\n", a.Postgres)
		if a.Postgres == PostgresCNPG && a.Cloud != CloudKind {
			// Cloud-durable defaults the report §1 requires (HA + WAL to bucket).
			b.WriteString("  # Cloud-durable defaults (report §1): 3 instances, zone spread, WAL to bucket.\n")
			b.WriteString("  instances: 3\n")
			fmt.Fprintf(&b, "  walArchive:\n    bucket: %q\n", a.Bucket)
		}
		b.WriteString("\n")
	}

	// --- Retrieval / embedding dimension pin --------------------------------
	b.WriteString("# Vector dimension pinned to the embed model (report §2 caveat: a change\n")
	b.WriteString("# forces an OpenSearch reindex — pin ONE dimension per install).\n")
	fmt.Fprintf(&b, "retrieval:\n  knnDimension: %d\n\n", a.KNNDimension)

	// --- LiteLLM tier aliases -----------------------------------------------
	// Only the model ids move; api_base / keyless auth is set by the overlay.
	tiers := map[string]string{
		"sovereign-reasoning": a.LLM.Reasoning,
		"sovereign-default":   a.LLM.Default,
		"sovereign-embed":     a.LLM.Embed,
	}
	b.WriteString("# LiteLLM tier model ids (the three aliases the agents route to). The overlay\n")
	b.WriteString("# sets api_base + keyless auth per provider; only the model id is chosen here.\n")
	b.WriteString("litellm:\n  proxy_config:\n    model_list:\n")
	for _, name := range sortedTierNames(tiers) {
		fmt.Fprintf(&b, "      - model_name: %s\n", name)
		fmt.Fprintf(&b, "        litellm_params:\n          model: %q\n", tiers[name])
	}
	b.WriteString("\n")

	// --- Ingress / TLS (optional) -------------------------------------------
	if a.Domain != "" {
		b.WriteString("# Ingress host + TLS (optional). cert-manager issues the cert when tls=true.\n")
		fmt.Fprintf(&b, "ingress:\n  enabled: true\n  hosts:\n    osUI: %q\n", "os."+a.Domain)
		if a.TLS {
			b.WriteString("  tlsIssuer: letsencrypt-prod\n")
		}
		b.WriteString("\n")
	} else {
		b.WriteString("# No domain given — ingress disabled (reach the OS via port-forward / cluster IP).\n")
		b.WriteString("ingress:\n  enabled: false\n")
	}

	return b.String()
}

// HelmArgs builds the argv (after `helm`) for the install, honoring the release
// name/namespace and the layered values files. The generated install.yaml path
// is appended LAST so it wins. Returned as a slice so the orchestrator can exec
// without a shell (no injection, no quoting surprises).
func HelmArgs(release, namespace, chartPath, overlayPath, installYAMLPath string) []string {
	args := []string{
		"upgrade", "--install", release, chartPath,
		"--namespace", namespace, "--create-namespace",
	}
	if overlayPath != "" {
		args = append(args, "-f", overlayPath)
	}
	args = append(args, "-f", installYAMLPath, "--wait", "--timeout", "15m")
	return args
}

// PlannedCommands returns the human-readable sequence the wizard will run, for
// --dry-run and the pre-run confirmation. Never includes secrets.
func PlannedCommands(a Answers, release, namespace, chartPath, bootstrapPath, installYAMLPath string) []string {
	var cmds []string
	if bootstrapPath != "" {
		cmds = append(cmds, fmt.Sprintf("bash %s   # provision keyless identity + bucket + managed-LLM access", bootstrapPath))
	}
	helm := append([]string{"helm"}, HelmArgs(release, namespace, chartPath, a.ValuesFile(), installYAMLPath)...)
	cmds = append(cmds, strings.Join(helm, " "))
	return cmds
}
